name: Build & Push (Scaleway)

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    # 🔴 IMPORTANT : cible l'Environment GitHub "project"
    environment: project

    env:
      # vars d'environnement (onglet Variables de l'Environment)
      REGISTRY: ${{ vars.SCW_REGISTRY }}          # ex: rg.fr-par.scw.cloud
      NAMESPACE: ${{ vars.SCW_NAMESPACE }}        # ex: project-annuel
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      VITE_FRONTEND_URL: ${{ vars.VITE_FRONTEND_URL }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Scaleway Registry
        run: |
          echo "${{ secrets.SCW_REGISTRY_PASSWORD }}" \
            | docker login "${REGISTRY}/${NAMESPACE}" -u nologin --password-stdin

      - name: Build & Push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/vegn-bio-api:latest
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/vegn-bio-api:${{ github.sha }}

      - name: Build & Push front
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          build-args: |
            VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
            VITE_FRONTEND_URL=${{ env.VITE_FRONTEND_URL }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/vegn-bio-front:latest
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/vegn-bio-front:${{ github.sha }}
